SELECT USER
FROM DUAL;
--==>> SCOTT

SELECT *
FROM TAB;

--○ 테이블 생성
CREATE TABLE TBL_MEMBERLIST
( ID VARCHAR2(30)       NOT NULL
, PW VARCHAR2(50)       NOT NULL
, NAME VARCHAR2(50)     NOT NULL
, TEL VARCHAR2(50)      NOT NULL
, EMAIL VARCHAR2(100)   
, CONSTRAINT MEMBERLIST_ID_PK PRIMARY KEY(ID)
);
--==>> Table TBL_MEMBERLIST이(가) 생성되었습니다.

--○ 





